schema: workflow/2022.04
name: AirTableStaleRowCollection
settings:
  error_notification: true
triggers:
- id: ti_ooT6kDR
steps:
- namespace: list_records
  runtime: nodejs18.x
  uses: airtable_oauth-list-records@0.0.2
  props:
    airtable:
      authProvisionId: apn_b6hwgEX
    baseId:
      __lv:
        label: DattoAlerts
        value: app4m2DT8q6ehwJR2
    tableId:
      __lv:
        label: Alerts
        value: tbldMxWMcwVt3R51P
- namespace: python
  runtime: python3.8
  uses: "./python/entry.py"

